# Docker compose version
version: "3.7"

# Define the services to be run
services:

  client: # name of the first service
    build: 
      context: ../client
      target: build
    image: gcr.io/viacom-poc/medialabs/client
    

  nginx:
    build:
      context: ../client
      target: nginx
    image: gcr.io/viacom-poc/medialabs/nginx
    ports:
      - "80:80"
    restart: unless-stopped

  server: # name of the second service
    build: 
      context: ../server
      target: server
    image: gcr.io/viacom-poc/medialabs/server # specify the directory of the Dockerfile
    ports:
      - "3000:3000" #specify ports mapping
